# Sample workflow for building a VitePress site and deploying it to GitHub Pages
name: Deploy VitePress site to Pages

# Uncomment the line below if your site is not at the root path
env:
  BASE_URL: "/vitepress/" # Defaults to "/"

on:
  # Disabled by default
  # To auto-deploy on push to main, uncomment the following lines:
  # push:
  #   branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions of GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Only allow one deployment at a time, skip queued runs between running and latest
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build with VitePress
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: .vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
